name: musify
description: Music Streaming app made in Flutter!
homepage: https://github.com/gokadzev/Musify
repository: https://github.com/gokadzev/Musify
issue_tracker: https://github.com/gokadzev/Musify/issues

publish_to: 'none'
version: 10.0.9+173 # run update.sh after changing the version

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  app_links: 7.0.0
  audio_service: ^0.18.18
  audio_session: ^0.2.3
  cached_network_image: ^3.4.1
  dynamic_color: ^1.8.1
  file_picker: ^11.0.2
  fluentui_system_icons: ^1.1.273
  flutter:
    sdk: flutter
  flutter_flip_card: '^0.0.6'
  flutter_localizations:
    sdk: flutter
  go_router: ^17.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.6
  http: ^1.6.0
  intl: ^0.20.2
  just_audio: 0.10.5
  path_provider: ^2.1.5
  receive_sharing_intent:
    path: ./packages/receive_sharing_intent
  rxdart: ^0.27.7
  url_launcher: ^6.3.2
  youtube_explode_dart:
    path: ./packages/youtube_explode_dart

dependency_overrides:
  just_audio:
    git:
      url: 'https://gitcode.com/CPF-Flutter/fluttertpc_just_audio.git'
      ref: master
      path: 'just_audio'
  url_launcher:
    git:
      url: 'https://gitcode.com/openharmony-tpc/flutter_packages.git'
      path: 'packages/url_launcher/url_launcher'
  go_router:
    git:
      url: 'https://gitcode.com/openharmony-tpc/flutter_packages.git'
      ref: master
      path: 'packages/go_router'
  audio_service:
    git:
      url: 'https://gitcode.com/CPF-Flutter/fluttertpc_audio_service.git'
      ref: master
      path: 'audio_service'
  audio_session:
    git:
      url: 'https://gitcode.com/CPF-Flutter/flutter_audio_session.git'
      ref: master
  path_provider:
    git:
      url: 'https://gitcode.com/openharmony-tpc/flutter_packages.git'
      path: 'packages/path_provider/path_provider'
  file_picker_ohos:
    git:
      url: 'https://gitcode.com/CPF-Flutter/fluttertpc_file_picker.git'
      ref: br_v10.3.8_ohos
      # path: ohos



dev_dependencies:
  # flutter_test:
  #   sdk: flutter



flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/licenses/
  fonts:
    - family: paytoneOne
      fonts:
        - asset: assets/fonts/paytone/PaytoneOne-Regular.ttf
