name: musify
version: 10.0.8+172 # run update.sh after changing the version

environment:
  sdk: '>=3.11.5 <4.0.0'
homepage: "https://github.com/gokadzev/Musify"
publish_to: none
description: "Music Streaming app made in Flutter!"
dependencies:

  app_links: 7.0.0
  audio_service: ^0.18.18
  audio_session: ^0.2.3
  cached_network_image: ^3.4.1
  dynamic_color: ^1.8.1
  file_picker: ^11.0.2
  fluentui_system_icons: ^1.1.273
  flutter:
    sdk: flutter
  flutter_flip_card: ^0.0.6
  flutter_localizations:
    sdk: flutter
  go_router: ^17.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.6
  http: ^1.6.0
  intl: ^0.20.2
  just_audio: 0.10.5
  just_audio_ohos:
    git:
      url: "https://gitcode.com/CPF-Flutter/fluttertpc_just_audio.git"
      ref: br_just_audio-v0.9.41_ohos
      path: "just_audio/ohos"
  path_provider: ^2.1.5
  receive_sharing_intent:
    path: ./packages/receive_sharing_intent
  rxdart: ^0.27.7
  url_launcher: ^6.3.2
  youtube_explode_dart:
    path: ./packages/youtube_explode_dart

dev_dependencies:
  flutter_launcher_icons: "^0.14.2"
  flutter_lints: ^5.0.0
  flutter_native_splash: "^2.2.19"
  flutter_test:
    sdk: flutter
  import_sorter: "^4.6.0"
  pubspec_dependency_sorter: "^1.0.5"
  translations_cleaner: "^0.0.5"
dependency_overrides:
  app_links:
    git:
      url: "https://gitcode.com/CPF-Flutter/fluttertpc_app_links"
      path: "app_links"
      ref: master
  audio_service:
    git:
      url: "https://gitcode.com/CPF-Flutter/fluttertpc_audio_service.git"
      ref: master
      path: "audio_service"
  audio_session:
    git:
      url: "https://gitcode.com/CPF-Flutter/flutter_audio_session.git"
      ref: br_v0.1.21_ohos
  file_picker:
    git:
      url: "https://gitcode.com/CPF-Flutter/fluttertpc_file_picker.git"
      ref: master
  go_router:
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      ref: master
      path: "packages/go_router"
  path_provider:
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      # ref: br_path_provider-v2.1.4_ohos
      path: "packages/path_provider/path_provider"

  url_launcher:
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      # ref: br_url_launcher-v6.3.0_ohos
      path: "packages/url_launcher/url_launcher"

  win32: 5.10.1


repository: "https://github.com/gokadzev/Musify"
issue_tracker: "https://github.com/gokadzev/Musify/issues"
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/licenses/
  fonts:
    - family: paytoneOne
      fonts:
        - asset: fonts/paytone/PaytoneOne-Regular.ttf
flutter_native_splash:
  color: "#f9fafd"
  image: "assets/images/ic_splash.png"
  color_dark: "#151515"
  image_dark: "assets/images/ic_splash.png"
  android_12:
    image: "assets/images/ic_splash.png"
    image_dark: "assets/images/ic_splash.png"
flutter_launcher_icons:
  android: true
  adaptive_icon_background: "#191919"
  adaptive_icon_foreground: "assets/images/ic_launcher_foreground.png"
  adaptive_icon_round: "assets/images/ic_launcher_round.png"
  adaptive_icon_monochrome: "assets/images/ic_launcher_foreground.png"
  image_path: "assets/images/ic_launcher.png"
  windows:
    generate: true
    image_path: "assets/images/ic_launcher_round.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/images/ic_launcher_round.png"
